version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: SpaceShop
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: spaceMarket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mydb111
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: